AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-serverless-e-commerce

  Sample SAM Template for aws-serverless-e-commerce

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: Stage name of the API. Default is dev.
    AllowedValues:
      - dev
      - qa
      - staging
      - prod
  DomainName:
    Type: String
    Description: The domain name for the API (e.g., api.example.com)
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: The Route53 Hosted Zone ID where the DNS record will be created
  AccessLogGroup:
    Type: String
    Description: Enter a name for the CloudWatch access log group

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    OpenApiVersion: 3.0.1
    TracingEnabled: true
    AccessLogSetting:
      DestinationArn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${AccessLogGroup}
      Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "caller":"$context.identity.caller", "user":"$context.identity.user","requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength" }'
    MethodSettings:
      - HttpMethod: '*'
        ResourcePath: '/*'
        LoggingLevel: INFO
        DataTraceEnabled: true
        MetricsEnabled: true
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
      AllowOrigin: "'*'"

Resources:
  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  ServerlessApi:
    Type: AWS::Serverless::Api
    DependsOn: ApiGatewayAccount
    Properties:
      Name: ProductPurchaseApi
      StageName: !Ref StageName

  ApiCustomDomain:
    Type: AWS::ApiGateway::DomainName
    DependsOn: ServerlessApi
    Properties:
      DomainName: !Ref DomainName
      RegionalCertificateArn: !Ref ApiCertificate
      EndpointConfiguration:
        Types:
          - REGIONAL
      SecurityPolicy: TLS_1_2

  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiCustomDomain
      RestApiId: !Ref ServerlessApi
      Stage: !Ref StageName

  ApiDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt ApiCustomDomain.RegionalHostedZoneId


  ProductPurchaseMessageSenderFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function that sends a message to SQS queue'
    Properties:
      FunctionName: ProductPurchaseMessageSender
      CodeUri: src/
      Handler: ProductPurchaseMessageSender.lambda_handler
      Runtime: python3.13
      Role: !GetAtt ProductPurchaseMessageSenderExecutionRole.Arn
      Environment:
        Variables:
          QUEUE_URL: !Ref ProductPurchaseQueue
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApi
            Path: /product-purchase
            Method: POST

  ProductPurchaseDataHandlerFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function that inserts product purchase data into DynamoDB table'
    Properties:
      FunctionName: ProductPurchaseDataHandler
      CodeUri: src/
      Handler: ProductPurchaseDataHandler.lambda_handler
      Runtime: python3.13
      Role: !GetAtt ProductPurchaseDataHandlerExecutionRole.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ProductPurchaseQueue.Arn
            BatchSize: 10

  ProductPurchaseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: product-purchase-queue
      SqsManagedSseEnabled: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProductPurchaseDLQ.Arn
        maxReceiveCount: 3

  ProductPurchaseDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: product-purchase-dlq
      MessageRetentionPeriod: 1209600
      SqsManagedSseEnabled: true

  ProductPurchaseTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: ProductPurchase
      PrimaryKey:
        Name: ProductPurchaseId
        Type: String
      SSESpecification:
        SSEEnabled: true

  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '${AccessLogGroup}'

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: apigateway.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'

  ProductPurchaseMessageSenderExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ProductPurchaseMessageSenderPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt ProductPurchaseQueue.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/productPurchaseMessageSender:*

  ProductPurchaseDataHandlerExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ProductPurchaseDataHandlerPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:PutItem"
                Resource: !GetAtt ProductPurchaseTable.Arn
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/productPurchaseDataHandler:*
              - Effect: Allow
                Action:
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                Resource: !GetAtt ProductPurchaseQueue.Arn
              - Effect: Allow
                Action:
                  - "sqs:SendMessage"
                Resource: !GetAtt ProductPurchaseDLQ.Arn

Outputs:
  ProductPurchaseApi:
    Description: API Gateway endpoint URL for ProductPurchase
    Value: !Sub "https://${ServerlessApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/product-purchase/"
  
  CustomDomainUrl:
    Description: Custom domain URL for the API
    Value: !Sub "https://${DomainName}/product-purchase/"
