AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-serverless-e-commerce

  Sample SAM Template for aws-serverless-e-commerce

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
      AllowOrigin: "'*'"

Resources:

  ProductPurchaseMessageSenderFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function that sends a message to SQS queue'
    Properties:
      FunctionName: productPurchaseMessageSender
      CodeUri: src/
      Handler: productPurchaseMessageSender.lambda_handler
      Runtime: python3.13
      Role: !GetAtt ProductPurchaseMessageSenderExecutionRole.Arn
      Environment:
        Variables:
          QUEUE_URL: !Ref ProductPurchaseQueue
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /purchase
            Method: POST

  ProductPurchaseDataHandlerFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function that inserts product purchase data into DynamoDB table'
    Properties:
      FunctionName: productPurchaseDataHandler
      CodeUri: src/
      Handler: productPurchaseDataHandler.lambda_handler
      Runtime: python3.13
      Role: !GetAtt ProductPurchaseDataHandlerExecutionRole.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ProductPurchaseQueue.Arn
            BatchSize: 10

  ProductPurchaseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: product-purchase-queue
      SqsManagedSseEnabled: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProductPurchaseDLQ.Arn
        maxReceiveCount: 3

  ProductPurchaseDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: product-purchase-dlq
      MessageRetentionPeriod: 1209600  # 14 days
      SqsManagedSseEnabled: true

  ProductPurchaseTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: ProductPurchase
      PrimaryKey:
        Name: ProductPurchaseId
        Type: String
      SSESpecification:
        SSEEnabled: true

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

  ProductPurchaseMessageSenderExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ProductPurchaseMessageSenderPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt ProductPurchaseQueue.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/productPurchaseMessageSender:*

  ProductPurchaseDataHandlerExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ProductPurchaseDataHandlerPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:PutItem"
                Resource: !GetAtt ProductPurchaseTable.Arn
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/productPurchaseDataHandler:*
              - Effect: Allow
                Action:
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                Resource: !GetAtt ProductPurchaseQueue.Arn
              - Effect: Allow
                Action:
                  - "sqs:SendMessage"
                Resource: !GetAtt ProductPurchaseDLQ.Arn

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProductPurchaseApi:
    Description: API Gateway endpoint URL for Prod stage for ProductPurchase function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/purchase/"
